version: '3.7'

services:
  nest-typeorm-costumrepo-override:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: yarn start:dev
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
